rules:
  braces: disable
  brackets: disable
  colons: {max-spaces-before: 0, max-spaces-after: 1}
  commas: disable
  comments: disable
  comments-indentation: disable
  document-end: disable
  document-start: disable
  empty-lines: disable
  empty-values: {forbid-in-block-mappings: true, forbid-in-flow-mappings: true}
  hyphens: {max-spaces-after: 1}
  indentation: disable
  key-duplicates: enable
  key-ordering: disable
  line-length: disable
  new-line-at-end-of-file: disable
  new-lines: {type: unix}
  quoted-strings: disable
  trailing-spaces: disable
  octal-values: enable
  truthy: disable
ignore:
  deploy/olm-catalog/ibm-monitoring-grafana-operator/1.9.2/ibm-monitoring-grafana-operator.v1.9.2.clusterserviceversion.yaml