apiVersion: operator.ibm.com/v1alpha1
kind: Grafana
metadata:
  labels:
    app.kubernetes.io/name: ibm-monitoring
    app.kubernetes.io/instance: common-monitoring
    app.kubernetes.io/managed-by: ibm-monitoring-grafana-operator
  name: ibm-monitoring
spec:
  service:
    ports:
      - name: ibm-monitoring-grafana
        protocol: TCP
        port: 3000
  resources:
    grafana: 2
    router: 1
    dashboard: 1
  ipVersion: "4"
  isHub: false
  tlsSecretName: ibm-monitoring-certs
  tlsClientSecretName: ibm-monitoring-certs
  prometheusServiceName: ibm-monitoring-prometheus
  prometheusServicePort: 9090
  # datasourceConfig:
  #   type: "openshift"