apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: ibm-monitoring
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/managed-by: ibm-monitoring-grafana-operator
    operatorframework.io/arch.s390x: supported
    operatorframework.io/os.linux: supported
    operatorframework.io/arch.amd64: supported
    operatorframework.io/arch.ppc64le: supported
  name: ibm-monitoring-grafana-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ibm-monitoring-grafana-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ibm-monitoring
        app.kubernetes.io/instance: grafana
        app.kubernetes.io/managed-by: ibm-monitoring-grafana-operator
        name: ibm-monitoring-grafana-operator
        intent: projected
      annotations:
        productName: IBM Cloud Platform Common Services
        productID: "068a62892a1e4db39641342e592daa25"
        productMetric: FREE
    spec:
      serviceAccountName: ibm-monitoring-grafana-operator
      hostIPC: false
      hostNetwork: false
      hostPID: false
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - ppc64le
                      - s390x
      containers:
        - name: grafana
          # Replace this with the built image name
          image: quay.io/opencloudio/ibm-monitoring-grafana-operator
          command:
            - ibm-monitoring-grafana-operator
          imagePullPolicy: Always
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          resources:
            limits:
              cpu: 50m
              memory: 512Mi
            requests:
              cpu: 20m
              memory: 64Mi
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['olm.targetNamespaces']
            - name: DASH_NAMESPACES
              valueFrom:
                configMapKeyRef:
                  name: namespace-scope
                  key: namespaces
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: ibm-monitoring-grafana-operator
            - name: GRAFANA_IMAGE
              value: quay.io/opencloudio/grafana@sha256:fff569b2a977f3a513e7d3934db19ecef0fb47ad3f3f5d5ad0afe555ed1ffeec
            - name: ROUTER_IMAGE
              value: quay.io/opencloudio/icp-management-ingress@sha256:da043f29eee4eaeb9a42945c075d1e9240958ccf2a9927770b056fb925d93c20
            - name: DASHBOARD_CTL_IMAGE
              value: quay.io/opencloudio/dashboard-controller@sha256:479f7509fbf2f3d72cbb888b1e0144c37de6fc9fc4eb46e7ec8880bb1773b888
            - name: INIT_IMAGE
              value: quay.io/opencloudio/icp-initcontainer@sha256:60699eab29e17db05963ed19f8bbd0c6124b2b6d19c2d2563698660f9f46997e
            - name: DS_PROXY_IMAGE
              value: quay.io/opencloudio/grafana-ocpthanos-proxy@sha256:47b3fa124af0c6b9f7deeaf3390f245d39d4a29794e499daa5e4a037d2a58294
