---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ibm-monitoring
    app.kubernetes.io/instance: common-monitoring
    app.kubernetes.io/managed-by: ibm-monitoring-grafana-operator
  creationTimestamp: null
  name: ibm-monitoring-grafana-scc
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - ibm-monitoring-grafana-scc
  resources:
  - securitycontextconstraints
  verbs:
  - use
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - create
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ibm-monitoring
    app.kubernetes.io/instance: common-monitoring
    app.kubernetes.io/managed-by: ibm-monitoring-grafana-operator
  creationTimestamp: null
  name: ibm-monitoring-grafana-dashboard
rules:
- apiGroups:
  - monitoringcontroller.cloud.ibm.com
  resources:
  - monitoringdashboards
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ibm-monitoring
    app.kubernetes.io/instance: common-monitoring
    app.kubernetes.io/managed-by: ibm-monitoring-grafana-operator
  creationTimestamp: null
  name: ibm-monitoring-grafana-operator
rules:
- nonResourceURLs: ["/metrics"]
  verbs:
  - get
- apiGroups:
  - certmanager.k8s.io
  resources:
  - clusterissuers
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: ibm-monitoring
    app.kubernetes.io/instance: common-monitoring
    app.kubernetes.io/managed-by: ibm-monitoring-grafana-operator
  creationTimestamp: null
  name: ibm-monitoring-grafana-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  - replicasets
  verbs:
  - '*'
- apiGroups:
  - certmanager.k8s.io
  resources:
  - certificates
  verbs:
  - '*'
- apiGroups:
  - operator.ibm.com
  resources:
  - grafanas
  - grafanas/finalizers
  - grafanas/status
  verbs:
  - '*'
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: ibm-monitoring
    app.kubernetes.io/instance: common-monitoring
    app.kubernetes.io/managed-by: ibm-monitoring-grafana-operator
  creationTimestamp: null
  name: ibm-monitoring-grafana
rules:
- apiGroups:
  - ""
  resources:
  - services
  - nodes
  - nodes/proxy
  - endpoints
  - pods
  - configmaps
  verbs:
  - get
  - list
  - watch